### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by heartacker** [kevinLiJ/NBARealTimeScore#14]
`Ctrl+shfit+L` 是官方默认的编辑快捷键。
非常不建议使用这个快捷键。导致现在windows 下编辑功能出现问题。
建议删除快捷键绑定或者使用如"<kbd>alt+shift+L</kbd>" 之类的

**Comment by heartacker** [comment]
@kevinLiJ 你好，请问可以取消这个快捷键吗？如果你使用macos。请问可以为winodws 用户考虑一下吗？
这个快捷键会严重影响windows 用户的用户肌肉记忆和编程体验。希望可以认真的考虑一下，谢谢你

**Comment by kevinLiJ** [comment]
好的，会在下次迭代取消快捷键，非常感谢反馈
